# XOR using RBF

In [1]:
import numpy as np
from math import exp

In [2]:
# XOR INPUTS
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
# CORRESPONDING XOR OUTPUTS
expected_output = np.array([[0],[1],[1],[0]])

In [3]:
# CENTRES FOR THE RBF
centres=np.array([[0,1],[1,0]])
theta1=[]
theta2=[]

In [4]:
# CALCULATING SQUARE DIFFERENCE B/W I/P AND CENTRE
for i in range(0,4):
    d1=((inputs[i][0]-centres[0][0])**2+(inputs[i][1]-centres[0][1])**2)
    d2=((inputs[i][0]-centres[1][0])**2+(inputs[i][1]-centres[1][1])**2)
    theta1.append(d1)
    theta2.append(d2)

In [15]:
print("SQUARE DIFFERENCE B/W I/P AND CENTRE")
print(theta1)
print(theta2)

SQUARE DIFFERENCE B/W I/P AND CENTRE
[1, 0, 2, 1]
[1, 2, 0, 1]


In [12]:
# GAUSSIAN 
gaussian=np.array([[exp(theta1[0]),exp(theta2[0]),1], 
                   [exp(theta1[1]),exp(theta2[1]),1], 
                   [exp(theta1[2]),exp(theta2[2]),1], 
                   [exp(theta1[3]),exp(theta2[3]),1]])

In [17]:
print("GAUSSIAN:\n",gaussian)
print()
print("GAUSSIAN TRANSPOSE\n",gaussian.T)

GAUSSIAN:
 [[2.71828183 2.71828183 1.        ]
 [1.         7.3890561  1.        ]
 [7.3890561  1.         1.        ]
 [2.71828183 2.71828183 1.        ]]

GAUSSIAN TRANSPOSE
 [[2.71828183 1.         7.3890561  2.71828183]
 [2.71828183 7.3890561  1.         2.71828183]
 [1.         1.         1.         1.        ]]


In [13]:
# MINIMUM NORM SOLUTION
g=(np.linalg.inv((gaussian.T).dot(gaussian)))
g1=(g.dot(gaussian.T))
weights=g1.dot(expected_output)
print("WEIGHTS:\n",weights)

WEIGHTS:
 [[ 0.33869689]
 [ 0.33869689]
 [-1.84134719]]


In [10]:
# OUTPUT CALCULATION USING PREDICTED WEIGHTS
prediction=[]
for i in range(0,4):
    output=weights[0]*exp(theta1[i])+weights[1]*exp(theta2[i])+weights[2]
    output=np.around(output,2)
    prediction.append(output)

In [11]:
print("PREDICTED OUTPUT\n",np.array(prediction))
print("EXPECTED OUTPUT\n",expected_output)

PREDICTED OUTPUT
 [[0.]
 [1.]
 [1.]
 [0.]]
EXPECTED OUTPUT
 [[0]
 [1]
 [1]
 [0]]
